### PR TITLE
added option to define localhost.localdomain and locahost6.localdomain6 ...

### PR DESCRIPTION
**Pull request by catalinpan**
added option to define localhost.localdomain and locahost6.localdomain6 for localhost_aliases and localhost6_aliases

### CODE REVIEW

**Comment by ghoneycutt** [comment]
localhost4.localdomain4 and localhost6.localdomain6 already exist. What are you wanting to accomplish?

**Comment by catalinpan** [comment]
Hi,

On the first puppet run facter detects the domain using either the first string after 127.0.0.1 or from resolv.conf. All the resources will be exported using that domain. As far as I can tell and from what I have tested with facter 2.2.0 the hosts module will update the first string after 127.0.0.1 to localhost.localdomain. On the second puppet the same server will export again the same resources but "as another server" because of the change in hosts. This will result in multiple entries from the same server in load balancers and other collectors. 

Example:

Before initial puppet run hosts file is like below example:

            127.0.0.1	     server_hostname.your_domain server_hostname localhost localhost4 localhost.localdomain localhost4.localdomain4

After initial puppet run hosts entries will look like this:

              127.0.0.1      localhost.localdomain  server_hostname.your_domain server_hostname localhost localhost4 localhost.localdomain localhost4.localdomain4

With the submitted change the entry "localhost.localdomain" can be customized in hiera with:

               hosts::localhost_localdomain: %{hostname}.your_domain

resulting in a host entry:

                127.0.0.1	     server_hostname.your_domain server_hostname localhost localhost4 localhost.localdomain localhost4.localdomain4

Having this little change facter managed to detect the correct domain.

Thanks

**Comment by ghoneycutt** [comment]
I think the issue is that you are mapping 127.0.0.1 to server.example.com, which is generally not done as your system would have an IP address and server.example.com would be associated with that.

**Comment by catalinpan** [comment]
Thanks for the reply. 
I have tried that but didn't work. I will run some more tests to make it working with the current module. Most probably I am missing something.

**Pull request closed without merging**
