### PR TITLE
Update stdlib dependency

### PR DESCRIPTION
**Pull request by kobybr**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@kobybr you have pulled in another commit. Think you need to rebase off of master.

**Comment by dploeger** [comment]
Can this be merged?

**Comment by dploeger** [comment]
@ghoneycutt Any idea when this gets released on the forge?

**Comment by ghoneycutt** [comment]
@dploeger Released in v2.8.0

**Comment by dploeger** [comment]
Awesome! Thanks.

**Comment by timdeluxe** [comment]
@ghoneycutt The release is not yet visible on puppet forge, can you please release v.2.8.0 to forge?

**Pull request merged**
