### PR TITLE
Normalize testing

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@Phil-Friderici any ideas here?

**Comment by Phil-Friderici** [comment]
Hej @ghoneycutt:
need to pin metadata-json-lint to the last version working with Ruby 1.9.3:
https://github.com/Phil-Friderici/puppet-module-afs/blob/master/Gemfile#L26-L28

**Comment by Phil-Friderici** [comment]
updated my open PRs accordingly:
https://github.com/ghoneycutt/puppet-module-nsswitch/pull/49
https://github.com/ghoneycutt/puppet-module-ntp/pull/95
https://github.com/ghoneycutt/puppet-module-redhat/pull/18
https://github.com/ghoneycutt/puppet-module-vim/pull/36

**Comment by ghoneycutt** [comment]
Thank you!!

**Comment by ghoneycutt** [comment]
Released in v2.6.0

**Pull request merged**
