### PR TITLE
V3 fix

### PR DESCRIPTION
**Pull request by TJM**
@ghoneycutt - It looks like this work has been on the backburner. We had an issue with the exported resources on vagrant boxes, so I updated this code to be more "complete" ... I did not do anything with tests/docs/etc.

I simplified the logic, as in my opinion setting "enable_something" to `false` should not try to ensure that it is absent. It should just not try to add it. If they want to ensure that something is absent, that could be done with `purge => true` or a hosts entry with `ensure => absent`.

I also changed the localhost stuff a bit, as it was reversing a more correct setup with the fqdn first. I doubt there would ever be a need to customize the localhost domain name, but I made it a parameter anyhow. 

~tommy

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Taking a look now.. thanks!

**Comment by TJM** [comment]
working on docs... might change a few parameter names for consistency. 

Should we add the (redundant) $use_fqdn parameter, even just as a deprecated option, or let it fail?

**Comment by ghoneycutt** [comment]
Hi @TJM 

Thanks for your interest in this module and all the help! I've updated the v3 branch and have PR #65 open. What do you think? Running into issues with the type validation section of the spec tests. Any ideas?

**Comment by TJM** [comment]
Hi @ghoneycutt ,

I think maybe you force pushed against the branch I was branched from? I will take a look at your new v3 directly, once I figure out how to unscrew my local copy of it. For what its worth, it would have been handy if you had made another commit so I would have known what had changed since I last looked at it. :)

(wait to rebase/combine commits till the very end) :)

~tommy

**Comment by ghoneycutt** [comment]
Closing as we have simplified the module with v3.0.0

**Pull request closed without merging**
